// Generated by collada_converter.py

#include "torus_model.h"

#include <stdio.h>

#include "pbkpp_assert.h"

#define READ(target, size)                                       \
  if (fread((target), (size), 1, fp) != 1) {                     \
    PBKPP_ASSERT(!"Failed to read from d:\\models\\torus.mesh"); \
  }

#define READ_ARRAY(target, size, elements)                       \
  if (fread((target), (size), (elements), fp) != (elements)) {   \
    PBKPP_ASSERT(!"Failed to read from d:\\models\\torus.mesh"); \
  }

#define SKIP(size)                                             \
  if (fseek(fp, (size), SEEK_CUR)) {                           \
    PBKPP_ASSERT(!"Failed to seek in d:\\models\\torus.mesh"); \
  }

uint32_t TorusModel::GetVertexCount() const {
  FILE *fp = fopen("d:\\models\\torus.mesh", "rb");
  PBKPP_ASSERT(fp && "Failed to open d:\\models\\torus.mesh");
  uint32_t num_vertices;
  READ(&num_vertices, sizeof(num_vertices))
  fclose(fp);
  return num_vertices;
}

const float *TorusModel::GetVertexPositions() {
  PBKPP_ASSERT(!vertices_ && "vertices_ already populated");
  FILE *fp = fopen("d:\\models\\torus.mesh", "rb");
  PBKPP_ASSERT(fp && "Failed to open d:\\models\\torus.mesh");
  SKIP(sizeof(uint32_t))

  uint32_t num_positions;
  READ(&num_positions, sizeof(num_positions))

  vertices_ = new float[num_positions];
  READ_ARRAY(vertices_, sizeof(*vertices_), num_positions)
  fclose(fp);
  return vertices_;
}

const float *TorusModel::GetVertexNormals() {
  PBKPP_ASSERT(!normals_ && "normals_ already populated");
  FILE *fp = fopen("d:\\models\\torus.mesh", "rb");
  PBKPP_ASSERT(fp && "Failed to open d:\\models\\torus.mesh");
  SKIP(sizeof(uint32_t))

  uint32_t num_positions;
  READ(&num_positions, sizeof(num_positions))
  SKIP(sizeof(float) * num_positions)

  uint32_t num_normals;
  READ(&num_normals, sizeof(num_normals))
  normals_ = new float[num_normals];
  READ_ARRAY(normals_, sizeof(*normals_), num_normals)
  fclose(fp);

  return normals_;
}
